### PR TITLE
Allocate more RAM to the process running MACS2

### PR DESCRIPTION
**Pull request by jinmingda**
Many thanks to contributing to nf-core/atacseq!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/atacseq branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/atacseq)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/atacseq/tree/master/.github/CONTRIBUTING.md

## Description

The memory footprint of macs2 is largely based on the size of the input BAM file. The label `process_long` used in "merge_library_macs" and "merge_replicate_macs" can only assign 2GB to the processes, which is hardly enough for many real human samples.

### CODE REVIEW

**Comment by drpatelh** [comment]
Would you mind also adding a separate PR (or you can do it here if you like) increasing the resource requirements for all of the `annotatePeaks` processes? After we have merged all of the changes it would be good if you are able to test the `dev` version of the pipeline using the `-r dev` parameter. Hopefully, it finishes without errors this time!

**Comment by drpatelh** [comment]
Added in BED download functionality from AWS iGenomes in the PR below along with some other minor changes:
https://github.com/nf-core/atacseq/pull/49

**Comment by jinmingda** [comment]
Hi @drpatelh, sorry I couldn't reply back to you asap since I wasn't at home yesterday. I will take a look at your review and work on the code later today.

**Comment by drpatelh** [comment]
Hi @jinmingda . No worries! Ive incorporated all the changes you suggested now. Can you check the open PR to see ive missed anything please and I'll add it in :+1: Thanks again.

**Comment by jinmingda** [comment]
@drpatelh I think your PR has incorporated everything I've found. However, it seems the description of using the staged blacklist file in makeGenomeFilter is not included in the CHANGELOG.

**Comment by drpatelh** [comment]
Good point. I'll add it in tomorrow. Thanks.

**Comment by drpatelh** [comment]
If there are any other improvements that you think that the pipeline would benefit from then let me know and I'll try and add them in. Probably going to do a minor release over the next couple of weeks to get the pipeline running on AWS without issue.

**Comment by jinmingda** [comment]
@drpatelh Sure! I will keep you informed if I find any bugs or things that can improve the pipeline.

**Pull request merged**
