### PR TITLE
retain optional columns from sample sheet

### PR DESCRIPTION
**Pull request by lnblum**
I gave it a go in adjusting samplesheet_check.py and input_check.nf to make sure additional columns are retained in the input samplesheet and the meta map. Happy to keep refining this if it makes sense. 
# nf-core/atacseq pull request

Many thanks for contributing to nf-core/atacseq!

Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).

## PR checklist

-  [ ] 1) Modified check_samplesheet.py to retain optional additional columns in the input sample sheet csv in the downstream sample sheet and 2) retain these additional columns in the "meta" map so that they can possibly be used downstream 
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/atacseq branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/atacseq)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/atacseq/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by drpatelh** [comment]
Hi @lnblum ! Thanks for the PR! I am a bit confused as to why we need to propagate non-mandatory fields in the samplesheet through the `meta` map if they aren't going to be used in the pipeline? I think this will make the pipeline more fragile to breaking e.g. due to weird formatting etc in the samplesheet.

We already publish a re-formatted samplesheet with all of the additional metadata as a separate samplesheet that can be re-used downstream? Or you could even use the original one if you like 🤔 
https://github.com/nf-core/atacseq/blob/f327c86324427c64716be09c98634ae0bc8165f6/bin/check_design.py#L26

**Comment by lnblum** [comment]
Hi @drpatelh,  that makes sense.  It turns out I might not need to make downstream edits using the meta map if I use the multiqc_sources.txt file to parse the outputs. 

From my testing, I didn't find the samplesheeet.valid.csv to keep additional columns, if that is the reformatted samplesheet you are referring to. I think it would be helpful if it did. I could use the original design sheet but the sample names get changed in the reformatted one (e.g. "*_T1"), although I could work around that. Thanks!

**Comment by lnblum** [comment]
Hi, just a note to say that I tested adding additional columns and it works now, (or always did ;). They are retained in the samplesheet.valid.csv. Thanks!

**Comment by drpatelh** [comment]
I actually added this functionality here:
https://github.com/nf-core/atacseq/blob/05a4e8b85782f3f4c52963caffc8729d1b079914/bin/check_samplesheet.py#L119

In this PR: https://github.com/nf-core/atacseq/pull/229

Thanks for confirming that it is working!

**Pull request closed without merging**
