### PR TITLE
Computemarix tssfix 193

### PR DESCRIPTION
**Pull request by robsyme**
# TSS heatmap inconsistency Fix

Fixes for the Deeptools matrix computation which flows to heatmap generation, fixing issue https://github.com/nf-core/atacseq/issues/193.

Previously, we were passing the gene bed file, when we should have been passing the tss bed file. The TSS bed file as it is currently generated produces a list of regions 1bp wide, specifying just the TSS start site. These regions are too small for the deeptools computeMatrix step to handle. By default, the minimum bin width is 10bp and regions smaller than this are discarded by deeptools. This PR also includes an awk snippet that expands any regions smaller than 10bp in the bed file to meet the 10bp window size minimum.

## PR checklist

- [X] This comment contains a description of changes (with reason)
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If necessary, also make a PR on the [nf-core/atacseq branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/atacseq)
- [X] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [X] Make sure your code lints (`nf-core lint .`).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/atacseq/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by robsyme** [comment]
This is not yet ready for review, apologies.

**Comment by robsyme** [comment]
I've rebased and squashed my initial attempt at this fix as there was a very simple fix available.

We produce two plots using deeptools - the profile plot over the whole transcript using `computeMatrix scale-regions` tool
image

... and the plot over just the TSS and surrounding 3kb using the `computeMatrix reference-point` tool (figure truncated for brevity):
image

We can re-use the existing nf-core module without modification (huge thanks to the original authors for envisaging this predicament) changing only module configuration with `ext.args`. Other tools remain

**Comment by robsyme** [comment]
The argument could be made that the "genes" label (taken from the bed file name) is not particularly informative, but it appears that `plotHeatmap` does not provide an option to remove those labels in the profiler tool.

**Comment by drpatelh** [comment]
Great thanks @robsyme !

**Review by drpatelh — APPROVED** [review]

**Pull request merged**
