### PR TITLE
Make it possible to run pipeline offline

### PR DESCRIPTION
**Pull request by ewels**
This extra code handles the error when we can't fetch the remote config file.

Offline:

```
nextflow run ../main.nf -profile test,docker,uppmax
N E X T F L O W  ~  version 19.01.0
Launching `../main.nf` [naughty_edison] - revision: 074596ffb0
Unknown configuration profile: 'uppmax'
```
(remote config didn't load, so we don't know what the `uppmax` config is - pipeline runs normally without this).

Online:

```
nextflow run ../main.nf -profile test,docker,uppmax
N E X T F L O W  ~  version 19.01.0
Launching `../main.nf` [nostalgic_hawking] - revision: 074596ffb0
ERROR ~ Cannot enable more than one container engine -- Choose either one of: docker, singularity

 -- Check '.nextflow.log' file for details
```
(We get an error because of conflicting config profiles, showing that the uppmax load worked properly).

Partial fix for nf-core/configs#1

Phil

### CODE REVIEW

**Comment by drpatelh** [comment]
Super simple but effective!

**Comment by drpatelh** [comment]
https://github.com/nf-core/tools/issues/240

**Comment by alneberg** [comment]
@ewels, great work! These changes should be made on the pipeline template as well, though?

**Comment by drpatelh** [comment]
https://github.com/nf-core/tools/pull/272

**Comment by alneberg** [comment]
Ah, brilliant!

**Comment by ewels** [comment]
Needs https://github.com/nf-core/configs/pull/17 to be merged before this will work. But should actually give full support for running offline now (rather than _just_ failing gracefully).

**Comment by drpatelh** [comment]
Nice! Thanks for the fix @ewels :tada:

**Pull request merged**
