### PR TITLE
Wip clarification usage

### PR DESCRIPTION
**Pull request by VErconi**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/atacseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/atacseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by bjlang — APPROVED** [review]
🚀

**Comment by VErconi** [comment]
This pull request contains an update of the usage.md file to address the following request of clarification #337

**Comment by bjlang** [comment]
@nf-core-bot fix linting

**Review by JoseEspinosa — APPROVED** [review]
LGTM 🚀 
Thanks a lot!

**Comment by JoseEspinosa** [comment]
Will merge with the lint error as the changes fixing it are already added in #360

**Pull request merged**
