### PR TITLE
Update template code to tools v1.5 and bug fixes

### PR DESCRIPTION
**Pull request by drpatelh**
* Big updates to bring template in line with `tools/v1.5`
* Removed Singularity file
* Added nf-core logo to email template (pinched from rnaseq) :wink:
* Create `csv` file for software versions (pinched from rnaseq) :wink:
* Can use `.fq.gz` files as input now
* Handles design's with more than 9 replicates i.e. double-digits
* Updated docs.

### CODE REVIEW

**Comment by drpatelh** [comment]
@ewels @apeltzer Travis is failing due to invalid conda checks during the linting. Markdown linting is passing and pipeline tests are passing too. 

Is it ok to merge this? There's some big changes that you may or may not want to go through!

Have updated `environment.yml` so will need to create a new Docker image after the merge.

**Comment by ewels** [comment]
> Have updated `environment.yml` so will need to create a new Docker image after the merge.

Docker hub will automatically build a new image when the PR is merged, so no need to worry about that.

**Comment by drpatelh** [comment]
Sorry! That's what I meant.

**Comment by drpatelh** [comment]
Meant having a working Docker image before the release.

**Comment by ewels** [comment]
Need to fix the linting problems ASAP, but that will require a new tools release. So happy to merge this now..

**Comment by ewels** [comment]
oops: https://cloud.docker.com/u/nfcore/repository/docker/nfcore/atacseq/builds/dbf1fe37-720b-4c26-a63c-11ecf1e98d89

```
Solving environment: ...working...
failed
UnsatisfiableError: The following specifications were found to be in conflict:
- bedtools=2.28.0
- ucsc-bedgraphtobigwig=377
Use "conda search <package> --info" to see the dependencies for each package.
```

**Comment by drpatelh** [comment]
Mannnnn! Just my luck. I can change it back to the old version of BEDTools. I think I'll test the conda environment first this time!

Our servers are down for the weekend so I'll sort it out at the Hackathon.

**Comment by ewels** [comment]
> Create csv file for software versions (pinched from rnaseq) 😉 

I don't think that this is in the template. Or the MultiQC plot export config. If it's of general use we should add them there so that it goes out for all pipelines.

**Comment by drpatelh** [comment]
Yep. No probs. I'll add it to a PR I am working on at the moment.

**Pull request merged**
